NAME: CMAKE

ON:
  PULL:
    branches: [ "main" ]
  PUSH:
    branches: [ "master" ]

ENV:
  BUILD_TYPE: Release


jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
    - use: actions/checkout@v3
    - name: Configure CMAKE
    
      ##  CMAKE_BUILD_TYPE is only required if you are using a single-configuration generator such as make. Configure CMAKE in a 'BUILD' subdirectory
    
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      ##  Build your program with the configuration file
    - name: BUILD
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      ##  See http://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail.
    - name: __TEST__
    
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}


  _ENV:
    - BUILD_TYPE: Release
      ##  Customize the CMake build type here

    - NAME: "__rc: crt: "



"clearTimeoutOrWWWMobile", nullptr]}, 1], ["cr:8080", [" "]]
"setTimeoutOrWWWMobile", null]}, -1], ["cr: 405", ["promiseimpl"]]


"createproc", null, 0]}, 1],  ["cr: ", [" "]]
"killprocessoncancel", 0]}, 1], ["crt:" null, [" "]]
{"crt: " : "db", ["_resTxt" : "[ ! ]", {["createproc", null, -1]}, 1], "crt: " : [null, null]}

"createdir", null, 0]}, -1], ["crt: " : "db", ["_UnexpectedUseInComet"]]


["promisemonitor", nullptr]
{["promiseimpl", null, 1]}, ["cr:",["__rc.__METAJSON__"], {"__rc", null, __rc.__METAJSON__"]}, 0], ["crt: " : "db", {"__rc" : [null], "__status__" :0, 1}, ["crt: " : "db", {["_UnexpectedUseInComet"]},
{"__rc", "_UnexpectedUseInComet", null]}, -1], "crt: ", ["promisemonitor"]}


{"_timesliceimpl", null, -1]}, ["crt: " : "db", [" "]]
[{"RunWAPP", null}, 1], ["crt: " : "db", [null, "_timesliceimpl"]]


_WAPP:
